name: CI/CD

on:
  push:
    branches: [master]
jobs:
  test-suite:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-branches
        uses: actions/checkout@v2
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
      - name: unittest
        run: |
          python -m unittest discover src/
      - name: install and run flake8
        run: |
          python -m pip install flake8
          python -m flake8 src/
      - name: install and run mypy
        run: |
          python -m pip install mypy
          python -m mypy src/ --ignore-missing-imports
  deployment:
    needs: test-suite
    runs-on: ubuntu-latest
    steps:
      - name: Fresh clone and install
        uses: appleboy/ssh-action@master
        with:
          host: 18.211.85.209
          username: github-actions
          key: ${{ secrets.KEY }}
          port: 22
          script: |
            rm -rf poke_viewer
            git clone https://github.com/mo-ccc/poke_viewer.git
            python3.8 -m venv poke_viewer/env
            source poke_viewer/env/bin/activate
            pip install -r poke_viewer/requirements.txt
          
      

    